### ISSUE TITLE
API 里面用到的那个 pbtxt 文件是怎么生成的？

### ISSUE THREAD

**Issue by BiggerHao** [koth/kcws#16]
希望作者能在 README 里提一下。
我试了一下执行这个命令
`python tensorflow/tensorflow/python/tools/freeze_graph.py --input_graph kcws/logs/graph.pbtxt --input_checkpoint kcws/logs/checkpoint --output_node_names "transitions,BatchMatMul_1" --output_graph kcws/kcws/models/final.pbtxt`
但是会报错，不知道是不是我哪个参数弄得不对。错误如下
```
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "tensorflow/tensorflow/python/tools/freeze_graph.py", line 135, in <module>
    tf.app.run()
  File "/Users/zhongya/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/tensorflow/python/tools/freeze_graph.py", line 132, in main
    FLAGS.output_graph, FLAGS.clear_devices, FLAGS.initializer_nodes)
  File "tensorflow/tensorflow/python/tools/freeze_graph.py", line 117, in freeze_graph
    sess.run([restore_op_name], {filename_tensor_name: input_checkpoint})
  File "/Users/zhongya/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/Users/zhongya/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/zhongya/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/Users/zhongya/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_23 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_23/tensor_names, save/RestoreV2_23/shape_and_slices)]]

Caused by op u'save/RestoreV2_23', defined at:
  File "tensorflow/tensorflow/python/tools/freeze_graph.py", line 135, in <module>
    tf.app.run()
  File "/Users/zhongya/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tensorflow/tensorflow/python/tools/freeze_graph.py", line 132, in main
    FLAGS.output_graph, FLAGS.clear_devices, FLAGS.initializer_nodes)
  File "tensorflow/tensorflow/python/tools/freeze_graph.py", line 104, in freeze_graph
    _ = tf.import_graph_def(input_graph_def, name="")
  File "/Users/zhongya/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
    op_def=op_def)
  File "/Users/zhongya/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2371, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/zhongya/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1258, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): Unable to open table file kcws/logs/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_23 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_23/tensor_names, save/RestoreV2_23/shape_and_slices)]]
```

**Comment by koth** [comment]
在tensorflow目录下运行，你的kcws/logs/checkpoint这个参数看起来不对，logs目录下一般有model.ckpt.meta ,model.ckpt.index, model.ckpt.data-xxxxxx-of-yyyyy
对应这个你填：--input_checkpoint kcws/logs/model.ckpt
