### ISSUE TITLE
标注模型执行freeze_graph.py脚本出错

### ISSUE THREAD

**Issue by dengzz** [koth/kcws#55]
标注模型是否少了输出GraphDef文件的步骤？
参考seg_model.pdtxt的生成方式使用freeze_graph.py脚本来生成pos_model.pbtxt。
命令如下：

 python tools/freeze_graph.py --input_graph pos_logs/graph.pbtxt --input_checkpoint pos_logs/model.ckpt --output_node_names "transitions,Reshape_7" --output_graph kcws/models/pos_model.pbtxt 

当执行以上命令时，抛错：

Traceback (most recent call last):
  File "train.py", line 211, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 139, in main
    FLAGS.variable_names_blacklist)
  File "train.py", line 94, in freeze_graph
    text_format.Merge(f.read().decode("utf-8"), input_graph_def)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 662, in _MergeField
    tokenizer.Consume(':')
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 1016, in Consume
    if not self.TryConsume(token):
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 1003, in TryConsume
    self.NextToken()
  File "/usr/lib/python2.7/site-packages/google/protobuf/text_format.py", line 1236, in NextToken
    match = self._TOKEN.match(self._current_line, self._column)
MemoryError

**Comment by koth** [comment]
加上模型导出了，你再试试
