### ISSUE TITLE
./bazel-bin/kcws/train/generate_training    UTF-8 Error 

### ISSUE THREAD

**Issue by tonyatml** [koth/kcws#9]
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
'utf8' codec can't decode bytes in position 0-1: unexpected end of data
'utf8' codec can't decode bytes in position 0-1: unexpected end of data^C
Traceback (most recent call last):
  File "/home/ml/py27env/kcws/bazel-bin/kcws/train/generate_training.runfiles/__main__/kcws/train/generate_training.py", line 155, in <module>
    main(len(sys.argv), sys.argv)
  File "/home/ml/py27env/kcws/bazel-bin/kcws/train/generate_training.runfiles/__main__/kcws/train/generate_training.py", line 147, in main
    processLine(line, out, vob)
  File "/home/ml/py27env/kcws/bazel-bin/kcws/train/generate_training.runfiles/__main__/kcws/train/generate_training.py", line 122, in processLine
    print e
KeyboardInterrupt

**Comment by Chanism** [comment]
这个可以忽略，别手动中断，它会执行完的，没影响

**Comment by koth** [comment]
去掉了 里面有些字符有问题
