### ISSUE TITLE
词性标注模型最后一步报错 MemoryError

### ISSUE THREAD

**Issue by kinghuangdd** [koth/kcws#92]
$ python tools/freeze_graph.py --input_graph pos_logs/graph.pbtxt --input_checkpoint pos_logs/model.ckpt --output_node_names "transitions,Reshape_9" --output_graph kcws/models/pos_model.pbtxt
Traceback (most recent call last):
  File "tools/freeze_graph.py", line 202, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tools/freeze_graph.py", line 134, in main
    FLAGS.variable_names_blacklist)
  File "tools/freeze_graph.py", line 93, in freeze_graph
    text_format.Merge(f.read().decode("utf-8"), input_graph_def)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 525, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 579, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 612, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 627, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 815, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 815, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 815, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 815, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 714, in _MergeField
    tokenizer.Consume(':')
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1078, in Consume
    if not self.TryConsume(token):
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1065, in TryConsume
    self.NextToken()
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1314, in NextToken
    match = self._TOKEN.match(self._current_line, self._column)
MemoryError

**Comment by kinghuangdd** [comment]
python是64位的 查看内存使用只用了1/4  怎么还报memoryError？

**Comment by younger911** [comment]
我也是同样的问题，之前有人问是否标注模型是否少了输出GraphDef文件的步骤，koth大大说加上模型导出了，我重新check下来仍然是同样的错误。

**Comment by chiangchiuti** [comment]
I have the same problem.
I successfully export the frozen model by changing the graph.pbtxt to grapg.pb and add a the argument  '--input_binary=true'

**Comment by koth** [comment]
是的，freeze_graph.py指定 --input_binrary=true是可以解决这类问题的，前提是在训练代码里加上类似
tf.train.write_graph(sess.graph.as_graph_def(),
                                 FLAGS.log_dir, "graph.pb", as_text=False)
